name: trigger tests on a pull request and merge to main
on:
  push:
    branches: [ main ]

jobs:
  trigger-tests-on-a-pull-request:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: "ci"
    secrets: inherit
  