name: trigger tests on a pull request in develop
on:
  pull_request:
    branches: [ main ]
jobs:
  trigger-tests-on-a-pull-request:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: "development"
    secrets: inherit
  